spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 22703579106-9dm070cirm60ndt14oghvccavs3i8t29.apps.googleusercontent.com
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile